### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data

### ISSUE THREAD

**Issue by LudvigAstrom** [bengtner/batterycontrol#3]
Hi,

Ran into some trouble again. I got the script up and running this spring, but the raspberry I was using crashed shortly thereafter and I'm now trying to reset everything.

There seems to be a problem with json, have amateurishly linked it to json not being able to handle both getState and getPrices at the same time. Could it be?

I get the following when I try to run the script: 

> Traceback (most recent call last):
>   File "/home/pi/battery.py", line 639, in <module>
>     main()
>   File "/home/pi/battery.py", line 531, in main
>     battery_mode=batteryChargeCntrl.getState()
>   File "/home/pi/battery.py", line 86, in getState
>     return json.loads(response.text)['state']
>   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

I find it a bit strange though, got it up and running last time, and i can't see any updates since then?

Sincerely,
Ludvig

**Comment by bengtner** [comment]
Strange. It looks like HomaAssistant returns illegal data when you ask for the battery status, However, it seems like you have an old version of batterycontrol.py. The line numbers the traceback refers to are not the same. For instance line 531 in the latest version looks as follows'

'''
529 def main():
530
531     options=get_cmd_line_parameters()           # get command line  
532     bLogger=logger(LOGFILE, LOGLEVEL)
'''

The line the traceback refers to pops up att 569 in the latest version.

I suggest you start to update to latest version.

**Comment by LudvigAstrom** [comment]
Hi, thanks.

I used the "nextstep" version. I updated to "main" instead but still can't run it.

> Traceback (most recent call last):
>   File "/home/pi/battery.py", line 660, in <module>
>     main()
>   File "/home/pi/battery.py", line 561, in main
>     battery_mode = batteryChargeCntrl.getState()
>   File "/home/pi/battery.py", line 88, in getState
>     return json.loads(response.text)['state']
>   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

**Comment by LudvigAstrom** [comment]
I started from scratch and think it all got resolved when I updated my private tokens. Probably some mistake in the HA url or token then if your analysis is correct.

Thanks again!
